version: '3.9'
services:

  streamlit:
    build:
      context: ./streamlit
    ports:
      - 8501:8501
    # без этого не выводит принты в консоль
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - app
    container_name: streamlit

  imputation:
    build:
      context: ./imputation
    ports:
      - :8000
    restart: always
    networks:
      - app
    container_name: imputation
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - streamlit

#  xgboost:
#    build:
#      context: ./xgboost
#    ports:
#      - :8000
#    restart: always
#    networks:
#      - app
#    container_name: xgboost
#    environment:
#      - PYTHONUNBUFFERED=1
#    depends_on:
#      - streamlit
##
#  lstm:
#    build:
#      context: ./lstm
#    ports:
#      - :8000
#    restart: always
#    networks:
#      - app
#    container_name: lstm
#    environment:
#      - PYTHONUNBUFFERED=1
#    depends_on:
#      - streamlit
#
##  sarimags:
##    build:
##      context: ./sarimags
##    ports:
##      - :8000
##    restart: always
##    networks:
##      - app
##    container_name: sarimags
##    environment:
##      - PYTHONUNBUFFERED=1
##    depends_on:
##      - streamlit
#
#  holtwinters:
#    build:
#      context: ./holtwinters
#    ports:
#      - :8000
#    restart: always
#    networks:
#      - app
#    container_name: holtwinters
#    environment:
#      - PYTHONUNBUFFERED=1
#    depends_on:
#      - streamlit

networks:
  app:
    driver: bridge